# Template FUNDING.yml pour GitHub

[GitHub Sponsors](https://github.com/sponsors) | 
          `github: mfournigault` 

[Buy me a coffee](https://www.buymeacoffee.com/) | `buy_me_a_coffee: selfmaker`
